image: docker:stable-dind

services:
  - name: docker:dind

variables:
  GIT_SSL_NO_VERIFY: '1'
  DOCKER_DRIVER: 'overlay2'
  DOCKER_TLS_CERTDIR: ''
  PROJECT_NAME: 'college-mobile'
  TZ: 'Asia/Shanghai'

cache:
  key:
    files:
      - yarn.lock
  paths:
    - node_modules

stages:
  - build
  - deploy

build:
  image: node:14.17.3
  stage: build
  tags:
    - frontend
  only:
    - dev
    - beta
    - stable
  artifacts:
    name: '$CI_COMMIT_REF_SLUG'
    when: on_success
    expire_in: 1 week
    paths:
      - dist/build/app-plus
  script:
    - npm config set registry https://registry.npm.taobao.org --global
    - npm config set disturl https://npm.taobao.org/dist --global
    - yarn config set registry https://registry.npm.taobao.org --global
    - yarn config set disturl https://npm.taobao.org/dist --global
    - yarn
    - yarn build:app-plus

deploy:
  image: centos:latest
  stage: deploy
  tags:
    - frontend
  only:
    - dev
    - beta
    - stable
  script:
    - yum install -y epel-release
    - yum install -y zip openssh-clients sshpass
    - export TIME_STRING=`date '+%Y%m%d_%H%M%S'`
    - if [ "$CI_COMMIT_REF_NAME" = "dev" ]; then export FILE_NAME="${PROJECT_NAME}-alapha-${TIME_STRING}.wgt"; fi
    - if [ "$CI_COMMIT_REF_NAME" = "beta" ]; then export FILE_NAME="${PROJECT_NAME}-beta-${TIME_STRING}.wgt"; fi
    - if [ "$CI_COMMIT_REF_NAME" = "stable" ]; then export FILE_NAME="${PROJECT_NAME}-stable-${TIME_STRING}.wgt"; fi
    - if [ "$CI_COMMIT_REF_NAME" = "dev" ]; then export LATEST_FILE_NAME="${PROJECT_NAME}-alapha-latest.wgt"; fi
    - if [ "$CI_COMMIT_REF_NAME" = "beta" ]; then export LATEST_FILE_NAME="${PROJECT_NAME}-beta-latest.wgt"; fi
    - if [ "$CI_COMMIT_REF_NAME" = "stable" ]; then export LATEST_FILE_NAME="${PROJECT_NAME}-stable-latest.wgt"; fi
    - echo ${FE_SERVER_PASSWORD} > ./fe_server_password
    - zip ${FILE_NAME} ./dist/build/app-plus
    - sshpass -f fe_server_password scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${FILE_NAME} root@192.168.1.128:/home/dev/micro-file-center/main/college
    - zip ${LATEST_FILE_NAME} ./dist/build/app-plus
    - sshpass -f fe_server_password scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${LATEST_FILE_NAME} root@192.168.1.128:/home/dev/micro-file-center/main/college
